services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: monitoring
      WAIT_TIME: ${WAIT_TIME}
    ports:
      - '8000:8000'
#    networks:
#      - main_network
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: monitoring
    ports:
      - '5432:5432'
    volumes:
      - pg_storage:/var/lib/postgresql/data
#    networks:
#      - main_network
#networks:
#  main_network:
#    driver: bridge

volumes:
    pg_storage:
      driver: local
